services:
  database:
    image: docker.io/postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: example
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on: database
